#!/bin/sh
#PHPRC="/usr/local/etc/php5/cgi/php.ini"
#export PHPRC
PHP_FCGI_CHILDREN=0
export PHP_FCGI_CHILDREN
PHP_FCGI_MAX_REQUESTS=50
export PHP_FCGI_MAX_REQUESTS
export env
exec /hsphere/shared/php53/bin/php-cgi
